services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_outputs:/app/streamlit_outputs
      - ./.streamlit:/app/.streamlit
    restart: unless-stopped
